In [2]:
import pandas as pd

In [5]:
# Series de pandas

numeros = [3,4,5,6,7]
serie = pd.Series(numeros)
serie, type(serie)

(0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64,
 pandas.Series)

In [ ]:
# Crear un diccionario

data = {
    "Nombre": ["Juan", "Ana", "Pedro", "Cristian", "Lucia"],
    "Edad": [28, 24, 35, 30, 22],
    "Ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao"]
}

data, type(data)

({'Nombre': ['Juan', 'Ana', 'Pedro', 'Cristian', 'Lucia'],
  'Edad': [28, 24, 35, 30, 22],
  'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao']},
 dict)

In [ ]:
# Generar un DataFrame a partir de un diccionario

df = pd.DataFrame(data)
df

     Nombre  Edad     Ciudad
0      Juan    28     Madrid
1       Ana    24  Barcelona
2     Pedro    35   Valencia
3  Cristian    30    Sevilla
4     Lucia    22     Bilbao

In [ ]:
# Exportar dataframe a csv

df.to_csv("mis_datos.csv")

In [12]:
# Importar datos desde un archivo csv

mis_datos = pd.read_csv("mis_datos.csv", index_col=0)
mis_datos

     Nombre  Edad     Ciudad
0      Juan    28     Madrid
1       Ana    24  Barcelona
2     Pedro    35   Valencia
3  Cristian    30    Sevilla
4     Lucia    22     Bilbao