In [4]:
import pandas as pd

In [5]:
# Series de pandas

numeros = [3,4,5,6,7]
serie = pd.Series(numeros)
serie, type(serie)

(0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64,
 pandas.Series)

In [6]:
# Crear un diccionario

data = {
    "Nombre": ["Juan", "Ana", "Pedro", "Cristian", "Lucia"],
    "Edad": [28, 24, 35, 30, 22],
    "Ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao"]
}

data, type(data)

({'Nombre': ['Juan', 'Ana', 'Pedro', 'Cristian', 'Lucia'],
  'Edad': [28, 24, 35, 30, 22],
  'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao']},
 dict)

In [7]:
# Generar un DataFrame a partir de un diccionario

df = pd.DataFrame(data)
df

     Nombre  Edad     Ciudad
0      Juan    28     Madrid
1       Ana    24  Barcelona
2     Pedro    35   Valencia
3  Cristian    30    Sevilla
4     Lucia    22     Bilbao

In [8]:
# Exportar dataframe a csv

df.to_csv("mis_datos.csv")

In [9]:
# Importar datos desde un archivo csv

mis_datos = pd.read_csv("mis_datos.csv", index_col=0)
mis_datos

     Nombre  Edad     Ciudad
0      Juan    28     Madrid
1       Ana    24  Barcelona
2     Pedro    35   Valencia
3  Cristian    30    Sevilla
4     Lucia    22     Bilbao

In [10]:
# Seleccionar una columna

nombres = mis_datos["Nombre"]
nombres

0        Juan
1         Ana
2       Pedro
3    Cristian
4       Lucia
Name: Nombre, dtype: str

In [13]:
# Seleccionar varias columnas

mis_datos[["Nombre", "Ciudad"]]

     Nombre     Ciudad
0      Juan     Madrid
1       Ana  Barcelona
2     Pedro   Valencia
3  Cristian    Sevilla
4     Lucia     Bilbao

In [15]:
# Seleccionar una fila

fila = mis_datos.loc[2]
fila

Nombre       Pedro
Edad            35
Ciudad    Valencia
Name: 2, dtype: object

In [16]:
# Filtrar por una condición
mis_datos[mis_datos["Edad"]>23]

     Nombre  Edad     Ciudad
0      Juan    28     Madrid
1       Ana    24  Barcelona
2     Pedro    35   Valencia
3  Cristian    30    Sevilla

In [17]:
filtro = (mis_datos["Edad"] > 23) & (mis_datos["Nombre"].str.startswith("A"))
mis_datos[filtro]

  Nombre  Edad     Ciudad
1    Ana    24  Barcelona

In [ ]:
# Filtrar personas mayores de 23 años por query

mis_datos.query("Edad > 23")
mis_datos[mis_datos["Nombre"].isin(["Ana", "Juan"])]

  Nombre  Edad     Ciudad
0   Juan    28     Madrid
1    Ana    24  Barcelona

In [26]:
def nombres_long_5(nombre):
    return len(nombre) == 5

mis_datos[mis_datos["Nombre"].apply(nombres_long_5)]

  Nombre  Edad    Ciudad
2  Pedro    35  Valencia
4  Lucia    22    Bilbao

In [27]:
# Filtrar por rango

mis_datos[mis_datos["Edad"].between(25,35)]

     Nombre  Edad    Ciudad
0      Juan    28    Madrid
2     Pedro    35  Valencia
3  Cristian    30   Sevilla